version: '3.1'
services:
  jenkins:
    image: 'tkomagata/jenkins:latest-alpine'
    container_name: jenkins
    restart: always
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - '$PWD/data/jenkins:/var/jenkins_home'
